name: Deploy to Azure App Service

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., dev, staging, production)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment-specific variables
        id: vars
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}"
          case $ENVIRONMENT in
            "dev")
              echo "dev"
              ;;
            "staging")
              echo "staging"
              ;;
            "production")
              echo "PROD"
              ;;
            *)
              echo "Invalid environment"
              exit 1
              ;;
          esac

